# Generated by Django 3.1 on 2020-08-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('hash', models.CharField(max_length=81)),
                ('timestamp', models.CharField(max_length=80)),
            ],
        ),
    ]
